apiVersion: v1
kind: Service
metadata:
  name: {{ include "policy-gateway.fullname" . | default "policy-gateway" }}
  labels: { app.kubernetes.io/name: policy-gateway }
spec:
  selector: {{- toYaml .Values.targetApp.labels | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
